language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BrianPugh
  password:
    secure: FGtv5AnDzWS+spHMGWHn0hHn9d2apjC2FwLOhxMeBFLk07lhUTkfbpj8cfm41yE5A0SbxB5dOpMEY9xIXEE5Q1eJN4ZZcNYCc0Idm+t4UKL5ZshxWgZWYz4HASVsqkQsbP8F3/XU5FKaBpZxRzK477jQ0fk7gb2vGSIfpMwWz9QRiPmH5/bGa9WPepTCmi7A47ATgBQkGZE9wSMJzyab+nu14pqoIVBUbukar6+Vu/98yAINnmYg+6XH+ca7+2xx4n3FJh3pYY+ZCGzsUzl/Mgtxj6cX3mJlzRtcSzwTzyAa3Ibl1s+wvJqpbSJ7jbpFu53nQ4O3rZZu1rEY21d76kfGfZM/Bm/OhV3w7BWuvulrHRSpBvWm0dN2EadpPz9FLpSTBtOlKSGrHqESxSUlP3EmqBurKJNsVFSKHQtxSegkOODISJKArcgC2lPIioEYnAW96uN4pj54tE0i8JfXbZ4lJbtwG+GwroWfV685SsKdMic02UeRFost/Q2ZSAw1UihSvNT9mF9nfrYJESIn3n02gV0l/9Qp3+Iunzv9teNHiWMVqnBjdmdx57FNUgtKRYh1TV3Vpfip5IhuC6Hn2POz7+1dSkSL8Rjx2Al+6ilhiJO2Z343KkCtESY08oZgkcjxm0bWm3mZ+NEQi0cgH+Co46MQ/romHFnd0OCSbx0=
  on:
    tags: true
    repo: BrianPugh/lox
    python: 3.6
